UPDATE course_form SET course_status = 1
WHERE course_form_id = 2;
UPDATE course_form SET course_status = 1
WHERE course_form_id = 3;
UPDATE course_form SET course_status = 2
WHERE course_form_id = 4;
UPDATE course_form SET course_status = 1
WHERE course_form_id = 5;
UPDATE course_form SET course_status = 2
WHERE course_form_id = 6;
UPDATE course_form SET course_status = 1
WHERE course_form_id = 7;
UPDATE course_form SET course_status = 2
WHERE course_form_id = 8;
UPDATE course_form SET course_status = 1
WHERE course_form_id = 9;
UPDATE course_form SET course_status = 2
WHERE course_form_id = 10;
UPDATE course_form SET course_status = 1
WHERE course_form_id = 11;
UPDATE course_form SET course_status = 1
WHERE course_form_id = 2;